crowdbotics/django-scaffold

{{cookiecutter.project_slug}}/users/adapters.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
This sets the proper account adapters, adds registration vars, and pulls more settings from env vars when available.
=> Add account settings, pull more settings from env vars

{{cookiecutter.project_slug}}/Dockerfile, {{cookiecutter.project_slug}}/env_prod.tf, {{cookiecutter.project_slug}}/heroku.yml, {{cookiecutter.project_slug}}/variables.tf, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
This fixes multiple deploy issues. See commit comments for details.
=> Fix deploys

{{cookiecutter.project_slug}}/home/management/commands/generate_project_report.py
Adding a missing 3 on the command string
=> Adding a missing 3 on the command string

{{cookiecutter.project_slug}}/env_prod.tf
Enables ACM to have HTTPS turned on by default.
=> Enable automatic certificate management

{{cookiecutter.project_slug}}/home/management/commands/load_initial_data.py
This fixes the issue with registration emails being sent from `example.com`.
=> PLAT-623 - Add project name and domain to Site

{{cookiecutter.project_slug}}/env_prod.tf, {{cookiecutter.project_slug}}/variables.tf
Requires [this PR](https://github.com/crowdbotics/crowdbotics-slack-app/pull/1396) to be merged first.
=> Add crowdbotics_domain TF var and setup webhooks through Terraform

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
Ticket LInk: https://crowdbotics.atlassian.net/browse/PLAT-4670
=> PLAT-4670 set email backend to console if email host credentials aren't provided

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
Adds missing logging import to settings.py
=> Add logging to settings

{{cookiecutter.project_slug}}/Pipfile
Adding pillow as a dependency so we can use an ImageField in the article module
=> Adding pillow as a dependency for image field

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/home/management/commands/createsuperuserauto.py, {{cookiecutter.project_slug}}/home/management/commands/customchangepassword.py
Includes boto3 updates, adding pillow, and supporing superuser creation for projects with no username.
=> Merge to master

{{cookiecutter.project_slug}}/Pipfile
Needed ASAP to get cryptography pinned
=> Production release of scaffold

{{cookiecutter.project_slug}}/{% if cookiecutter.is_mobile == "y" %}web_build{% endif %}/index.html, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/urls.py
=> PLAT-4745: add react-native-web support for mobile scaffold

{{cookiecutter.project_slug}}/README.md
- added Table of Contents
- added Project Structure
- added Usage
=> django scaffold readme update pt1

{{cookiecutter.project_slug}}/README.md
replace incorrect (hardcoded) project slugs with cookiecutter tags in README
=> missing template tag in project structure

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/Pipfile.lock
Relates to https://github.com/crowdbotics/crowdbotics-slack-app/pull/3051
=> Remove fcm-django library and upgrade python to 3.8

{{cookiecutter.project_slug}}/modules/options.json, {{cookiecutter.project_slug}}/modules/options.py, {{cookiecutter.project_slug}}/modules/utils.py
Adding `options.json` to Django Scaffold to use with Python modules
=> PLAT-5714 Python Parser Upgrade (Django Scaffold)

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/urls.py
Ticket: https://crowdbotics.atlassian.net/browse/PLAT-9487
=> PLAT-9487 fix for react native web

{{cookiecutter.project_slug}}/README.md
https://crowdbotics.atlassian.net/browse/PLAT-9594?atlOrigin=eyJpIjoiY2VkYjA4MTIzOTlhNGZkMThhNTU4Njg5ZGJmNjhlYjYiLCJwIjoiaiJ9
This PR adds a minor update to the README of the Django Backend Scaffold on Security Configuration and how to enable it using environment variables through Crowdbotics Dashboard
[PLAT-9594]: https://crowdbotics.atlassian.net/browse/PLAT-9594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-9594 Add Security Config to README

hooks/post_gen_project.py, {{cookiecutter.project_slug}}/home/api/v1/serializers.py, {{cookiecutter.project_slug}}/home/apps.py, {{cookiecutter.project_slug}}/home/management/commands/createsuperuserauto.py, {{cookiecutter.project_slug}}/home/management/commands/customchangepassword.py, {{cookiecutter.project_slug}}/home/management/commands/upgradetosuperuser.py, {{cookiecutter.project_slug}}/home/migrations/0001_load_initial_data.py, {{cookiecutter.project_slug}}/home/views.py, {{cookiecutter.project_slug}}/manage.py, {{cookiecutter.project_slug}}/modules/admin.py, {{cookiecutter.project_slug}}/modules/apps.py, {{cookiecutter.project_slug}}/modules/urls.py, {{cookiecutter.project_slug}}/modules/utils.py, {{cookiecutter.project_slug}}/users/admin.py, {{cookiecutter.project_slug}}/users/forms.py, {{cookiecutter.project_slug}}/users/migrations/0001_initial.py, {{cookiecutter.project_slug}}/users/tests/factories.py, {{cookiecutter.project_slug}}/users/views.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/wsgi.py
chore(post_gen_project.py): fix formatting and add missing newline at end of file
chore(server.ts): change port variable case from lowercase port to uppercase PORT to improve semantics
feat(server.ts): add support for process.env.PORT environment variable to be able to run app on a configurable port
chore(serializers.py): fix formatting of field names in SignupSerializer and UserSerializer
feat(serializers.py): add required and allow_blank options to email field in SignupSerializer
chore(apps.py): fix formatting of name field in HomeConfig
chore(createsuperuserauto.py): fix formatting and typo in help message
chore(customchangepassword.py): fix formatting and typo in help message
chore(upgradetosuperuser.py): fix formatting and add missing newline at end of file …
=> Run Black Formatter

.github/app-release.yml
=> PLAT-11893-Add release configuration

.github/app-release.yml
- Update release workflow to use `crowdbotics/github-actions/create-github-release`
=> update GH workflow

.github/release.yml
=> Release 20240104

.github/workflows/release-to-qa.yml
Ticket: https://crowdbotics.atlassian.net/browse/CBDEVOPS-362
=> Update release-to-qa workflow to work with reusable github-actions

.github/workflows/create-github-release.yml, .github/workflows/release-to-qa.yml
This PR merges changes from develop into qa.
=> Merge develop into qa

{{cookiecutter.project_slug}}/Dockerfile
=> set python 3.9 for Dockerfile

.github/workflows/create-github-release.yml
- update `DJANGO_SCAFFOLD_REPO_BRANCH` env var on BE  when release tag is created.
=> CBDEVOPS-469 update DJANGO_SCAFFOLD_REPO_BRANCH on release

.github/workflows/create-github-release.yml
- enable slack notification for prod deployment
- Restrict production release to master branch
=> CBDEVOPS-478 enable slack notification for prod deployment

.github/workflows/create-github-release.yml
=> CBDEVOPS-503 fix django release workflow

.github/workflows/create-github-release.yml
CBDEVOPS-503 fix django release workflow
=> Hotfix: Add missing checkout step

{{cookiecutter.project_slug}}/home/api/v1/serializers.py, {{cookiecutter.project_slug}}/home/templates/base.html, {{cookiecutter.project_slug}}/home/templates/home/index.html, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
Fix prod deployment by adding `'allauth.account.middleware.AccountMiddleware'` to the `MIDDLEWARE`
=> Add allauth AccountMiddleware to MIDDLEWARE list

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/Pipfile.lock
Update Django version from 2.2.26 to 4.2.16 in Pipfile for compatibility with newer features
=> Upgrade Django version from 3.2.25 to 4.2.16 to leverage new features and improvements

.github/workflows/create-github-release.yml
- Removing this step as it is updated with other workflow i.e `build-deploy.yaml`
=> remove env update step
