cookiecutter.json, {{cookiecutter.project_slug}}/variables.tf
This removes the unused var `project_dash_slug`, adds `project_generated_name` (the project name with dashes), and uses it for the Heroku app name to match previous deployment settings.
=> Use generated_name for deployments

{{cookiecutter.project_slug}}/home/api/v1/serializers.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
The rest_auth reset password serializer uses Django's form. This doesn't work when using allauth. This PR replaces the form with allauth's reset password form.
Solution taken from https://stackoverflow.com/questions/26869309/django-rest-framework-django-allauth-password-reset-recovery/36365644#36365644
This one led me down a bit of a rabbit hole. To ensure this was the best fix I ended up looking at two rest_auth Github issues, two StackOverflow posts, the rest_auth source, and Django’s source.
=> Fix reset password API

{{cookiecutter.project_slug}}/Dockerfile
Pillow is used frequently enough that including its required system libs by default makes sense. They may also be used by other packages.
=> Add system libs for pillow

{{cookiecutter.project_slug}}/Dockerfile
This makes it easier to add dependencies that aren't included in the Alpine latest main repo.
=> Add testing apt repo for additional dependencies

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/urls.py
This PR adds swagger docs generation through the package `drf_yasg`.
The url for the web version of the docs is `/api-docs` and requires the user to be authenticated
=> Add swagger api docs to the scaffold

{{cookiecutter.project_slug}}/env_prod.tf, {{cookiecutter.project_slug}}/variables.tf
This allows us to pass in the secret key. Doing so will fix the first deploy failing and allow us to deploy once instead of twice.
To work properly this requires some changes to crowdbotics-slack. It's safe to merge this first. Until that's updated on first deploy it will use the default value but that will be overridden once Terraform is complete.
=> Add variable for secret key

{{cookiecutter.project_slug}}/main.tf
This upgrades the Heroku provider to the latest version. There shouldn't be any breaking changes. This is needed up upgrade Terraform to the latest version.
=> Update Heroku Terraform provider to 2.2.1

{{cookiecutter.project_slug}}/Dockerfile, {{cookiecutter.project_slug}}/Pipfile
alpine:latest is installing python 3.8 which has issues with some packages. For some reason python 3.7.5 isn't available on alpine:latest so I've pinned it to 3.10.
This also replaces the testing repo with community. Gdal has be added to community so testing should no longer be necessary.
I've removed the fcm-django conditional. It breaks dependabot automatic package upgrade PRs. Projects that don't use it can manually remove it. Having it installed shouldn't hurt anything.
=> Pin python 3.7.5 and alpine 3.10

{{cookiecutter.project_slug}}/home/api/v1/urls.py
Apparently DRF changed this and didn't put it in their changelog.
=> basename no longer has an underscore

{{cookiecutter.project_slug}}/home/management/commands/load_initial_data.py, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/urls.py
This updates files that were using single quote strings to double quotes. Projects with an apostrophe in the name were erroring out because of this.
Example error: https://sentry.io/organizations/crowdbotics-corporation/issues/1404728295/?project=1464774&referrer=alert_email
=> Allow apostrophes in project_name

{{cookiecutter.project_slug}}/.dockerignore, {{cookiecutter.project_slug}}/.env.example, {{cookiecutter.project_slug}}/.gitignore, {{cookiecutter.project_slug}}/Dockerfile, {{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/docker-compose.override.yml, {{cookiecutter.project_slug}}/docker-compose.yml
PLAT-1921
Some users experienced the limitations of the Alpine platform. Therefore,
it makes sense to switch to an LTS Ubuntu, which is easier to maintain, too.
- Postgres files are mounted to project subdirectory
- Heavy usage of `docker-compose.override.yml`, so it's easier to write
a deployment configuration.
- Users will also benefit from an expanded README including the docker
setup.
- Pinning of the versions in Docker related files will also ensure fewer
unwanted surprises in the future.
1. Make sure you have [Cookiecutter](https://github.com/cookiecutter/cookiecutter) installed, you can [brew](https://brew.sh/) it on MacOS.
1. Clone this branch
1. Then:
```sh
$ cookiecutter django-scaffold
```
`cd` into the newly created project and follow instrutions in README.md.
=> PLAT-1921: Update Docker configuration and instructions

{{cookiecutter.project_slug}}/Dockerfile
curl is required to stream logs to Heroku. Without it we won't get deploy error logs.
=> Add curl to Dockerfile for streaming logs

{{cookiecutter.project_slug}}/Dockerfile
pipenv finally released a new version but it's broken in Docker. We need to use the old version until they fix it.
=> Pin pipenv to 2018.11.26 since the latest version is broken

{{cookiecutter.project_slug}}/home/management/commands/customchangepassword.py
This gives correct message for user with password reset is successful. Also, this will be great help for checking if the password reset is successful while reseting password from dashboard. We can just check for this message instead of current implementation of checking for errors.
=> add superuser password reset successful message

{{cookiecutter.project_slug}}/Pipfile
This is needed because the latest version of the cryptography package requires rust to compile, which isn't available.
=> Pin cryptography package

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/Pipfile.lock
This commits Pipfile.lock to the scaffold. By adding it we can eliminate the need to run `pipenv lock` when generating a new project, significantly increasing the speed of creating and avoiding timeouts which occasionally occur.
I believe it was originally removed a long time ago when fcm-django was conditional because dependabot didn't like it. There shouldn't be an issue with having it committed. dependabot will help us keep everything updated.
=> Add Pipfile.lock

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/Pipfile.lock
For unknown reasons there's an error with boto3's hash that causes `pipenv install` to fail. Updating to 1.17.72 works. Tested in a review app.
=> Update boto3 to 1.17.72 to fix hash issue

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
Currently, fcm_django is removed from Pipfile but it exists in settings which is causing deployment issue with mobile app. This PR removed those lingering fcm_django related stuffs from settings.
=> fix fcm_django removal

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/Pipfile.lock
I've tested this with the new docker changes and it works. We no longer need to pin to <3.4.
I manually tested in [this review app](https://crowdbotics-slack-dev.herokuapp.com/dashboard/app/22836) and it worked without issues.
=> Upgrade cryptography to 3.4.7

{{cookiecutter.project_slug}}/.github/dependabot.yml
This setting will only update Pipfile.lock based on Pipfile rules which should prevent major update PRs that could cause issues (eg Django 3).
=> Use dependabot lockfile-only to avoid major updates

.github/dependabot.yml
The Dependabot team has requested that we remove all `day` and `time` settings from our config. This will avoid concentrating all runs at the same time and putting undo stress on their infrastructure.
=> Remove Dependabot schedule.day to allow for more flexible scheduling

{{cookiecutter.project_slug}}/.dockerignore, {{cookiecutter.project_slug}}/Dockerfile
[PLAT-6799](https://crowdbotics.atlassian.net/browse/PLAT-6799)
_Related ticket:_ [PLAT-5484](https://crowdbotics.atlassian.net/browse/PLAT-5484)
_Related PR:_ [Update Django Scaffold Docker image](https://github.com/crowdbotics/django-scaffold/pull/342)
Update `Dockerfile` to use a base image created in the `project-deploy/docker/cb-django/Dockerfile` to improve overall build speeds.
_Describe how a reviewer should test your PR_
* Pull the base image `crowdbotics/cb-django:3.8-slim-buster` from dockerhub .
* Checkout the PLAT-6799 branch
* Use `cookiecutter` to create a project from the template and cd into the project source folder
* Run `docker build -t <image-name:tag> --build-arg=SECRET_ENV=<some_super_secret_key> -f Dockerfile  .` 
Once the build succeeds the image should be …
=> PLAT-6799 Update Dockerfile and .dockerignore

{{cookiecutter.project_slug}}/home/management/commands/createsuperuserauto.py
While upgrading to superuser, we are checking if the user has verified email. To make createsuperuser consistent with that, we mark user has verified email while creating superuser.
=> PLAT-6911 updates

{{cookiecutter.project_slug}}/modules/utils.py
This PR fixes `get_options` get call that was looking for a `slug` property, which doesn't exist.
=> Fix get_options dict get call

{{cookiecutter.project_slug}}/.circleci/webhook_callback.sh
CIRCLE_COMPARE_URL env var isn't available from CircleCI version 2.1. So, it's giving error now while webook callback because of that. This will fix it.
=> remove compare_url from webhook callback

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/Pipfile.lock, {{cookiecutter.project_slug}}/modules/admin.py, {{cookiecutter.project_slug}}/modules/urls.py, {{cookiecutter.project_slug}}/modules/utils.py
- Update modules.utils
- Update modules.admin
- Update modules.urls
Implementation Details
======================
In order to support Django Modules as Python Packages, modules app's
utils, admin and urls discovery must be generalized to any subdirectory.
This is not a breaking change, as current Django Modules should work.
=> PLAT-7015: Django Modules as Python Packages

{{cookiecutter.project_slug}}/Dockerfile
PLAT-9829
_Related tickets:_
_Related PRs:_
The `/modules` folder was not copied on the .venv. This leads the Pipenv file to not find the Django module that was installed on the repository -> i.e: _Invalid path ‘./modules/camera’_
- Create an APP
- Add Django module on Studio
-  Deploy the app ( after the Module is installed )
- The deployment should succeed
- You should find the new Module's admin table on the Django Admin Panel of the App.
=> PLAT-9849 Local python packages installation fail on deployment

{{cookiecutter.project_slug}}/.circleci/generate_gcp_config.sh, {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
Ticket: https://crowdbotics.atlassian.net/browse/PLAT-9778
Changes:
Update gcp cloudbuild source as the project root, to use Dockerfile to build rn web while GCP deployment for mobile app.
This should be released along with https://github.com/crowdbotics/modules/pull/798
=> PLAT-9778 Update for rn web deployment with GCP

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
##Description of work done
Recent changes in AWS S3 policies to enforce `Bucket owner enforced` for all the newly created S3 buckets are not working with the current `AWS_DEFAULT_ACL` value of `public-read` we enforce. This is resulting in failed object uploads with permissions issues. 
- we need to use `bucket-owner-full-control` for the env var `AWS_DEFAULT_ACL` 
#Testing 
- Create a project
- Deploy API platform
- Add S3 addon form API settings tab
- Deploy API again
- Using the generated app/project code ( in crowdbotics-dev/apps repo ) add ImageField to one of the model (Have to manually create now, the FE doesn’t support this field now) and then add that model to admin.py and push the code.
- Deploy API again
- Create a superuser 
- Log in to the admin panel of the deployed app
- …
=> PLAT-11707-Update AWS_DEFAULT_ACL  env val

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
chore(settings.py): add DEFAULT_FROM_EMAIL configuration to set the default sender email address for the application's emails
=> Add DEFAULT_FROM_EMAIL to settings.py

{{cookiecutter.project_slug}}/Pipfile, {{cookiecutter.project_slug}}/Pipfile.lock, {{cookiecutter.project_slug}}/README.md
We started using the newer docker image `cb-django:3.9-slim-buster` but didn't update older references of python versions which breaks docker builds.
=> fix: remove python 3.7/3.8 references, use 3.9

{{cookiecutter.project_slug}}/.circleci/generate_azure_config.sh
Update `setup_remote_docker` version to `default`. This takes in the latest supported version. 
I have tested with this update, it works.
=> Fix: Azure deployment

{{cookiecutter.project_slug}}/Pipfile.lock
We recently have the outdated pipfile.lock file, which is causing the deployment to fail in the dev environment.
This PR update that outdated lock file. This will fix the deployment issue on dev.
=> Fix: Oupdated lock file

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/settings.py
[Jira Ticket:](https://crowdbotics.atlassian.net/browse/PI-465)
This change allows the application to specify trusted origins for CSRF protection, improving the overall security of the application.
=> PI-465: Add CSRF_TRUSTED_ORIGINS setting to enhance security and fix the 403 error on the Admin page

{{cookiecutter.project_slug}}/Pipfile.lock
The `Pipfile.lock` file is not in out of date and needs to be synced by running `pipenv lock`
=> PI-637: Update Pipfile.lock
